server:
  port: 9009
spring:
  rabbitmq:
    host: 192.168.25.190
aliyun:
  sms:
    template_code: SMS_137670376
    sign_name: Tree
    accessKeyId: LTAIm84IKu87WWqg
    accessKeySecret: zcrdRYvJ2vWfDYdf6Z5MXG7ypyHH1X
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    pprefer-ip-address: true
