server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.190:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    pprefer-ip-address: true


