server:
  port: 9006
spring:
  application:
    name: tensquare‐spit #指定服务名
  data:
    mongodb:
      host: 192.168.25.190
      port: 27017
      database: spitdb
  redis:
      host: 192.168.25.190
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    pprefer-ip-address: true
